import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ConfirmationService, MessageService } from 'primeng/api';
import { TableModule } from 'primeng/table';
import { ToastModule } from 'primeng/toast';

@Component({
  selector: 'app-info',
  standalone: true,
  imports: [TableModule, ToastModule, CommonModule],
  providers: [MessageService, ConfirmationService],
  templateUrl: './info.component.html',
  styleUrls: ['./info.component.scss'],
})
export class InfoComponent {
  levels = [
    {
      level: 6,
      english: 'CREATING',
      mongolian: 'БҮТЭЭХ',
      description:
        '(Бүтээлч сэтгэлгээ) Шинэ санаа, бүтээл хийх, эсвэл юмсыг өөр өнцгөөс харах арга зам',
      verbs: [
        // { en: 'create', mn: 'бүтээх' },
        // { en: 'invent', mn: 'зохион бүтээх' },
        { en: 'design', mn: 'загварчлах' },
        { en: 'modify', mn: 'шинэчлэх' },
        { en: 'develop', mn: 'боловсруулах' },
        // { en: 'write', mn: 'шинэчлэн бичих' },
        { en: 'construct', mn: 'байгуулах' },
        { en: 'design', mn: 'зохиомжлох' },
        { en: 'create', mn: 'зохион бүтээх' },
        { en: 'formulate', mn: 'томъёолох' },
        { en: 'hypothesize', mn: 'таамаглах' },
        { en: 'integrate', mn: 'нэгтгэх' },
        { en: 'invent', mn: 'нээлт хийх' },
        { en: 'make', mn: 'буй болгох' },
        { en: 'plan', mn: 'төлөвлөх' },
        { en: 'produce', mn: 'үйлдвэрлэх' },
        { en: 'assemble', mn: 'угсрах' },
        { en: 'combine', mn: 'нийлүүлэх' },
      ],
    },
    {
      level: 5,
      english: 'EVALUATING',
      mongolian: 'ҮНЭЛЭХ',
      description:
        '(Шүүмжлэлт сэтгэлгээ) Шийдэл эсвэл үйлдэж байгаа чиг хандлагчн зөв бурууг тунгаах',
      verbs: [
        // { en: 'criticize', mn: 'шүүн хэлэлцэх' },
        // { en: 'reframe', mn: 'дахин загварчлах' },
        // { en: 'judge', mn: 'шүүн тунгаах' },
        // { en: 'prioritize', mn: 'зэрэглэл тогтоох' },
        // { en: 'plan', mn: 'төлөвлөх' },
        { en: 'assess', mn: 'явцыг үнэлэх' },
        { en: 'check', mn: 'шалгах' },
        { en: 'criticize', mn: 'шүүмжлэх' },
        { en: 'detect', mn: 'илрүүлэх' },
        { en: 'differentiate', mn: 'ялгааг тогтоох' },
        { en: 'judge', mn: 'шүүх' },
        { en: 'measure', mn: 'хэмжих' },
        { en: 'monitor', mn: 'хянах' },
        { en: 'rank', mn: 'эрэмбэ тогтоох' },
        { en: 'test', mn: 'тестлэх' },
        { en: 'validate', mn: 'баталгаажуулах' },
      ],
    },
    {
      level: 4,
      english: 'ANALYZING',
      mongolian: 'ДҮН ШИНЖИЛГЭЭ ХИЙХ',
      description:
        '(Шүүмжлэлт сэтгэлгээ) Мэдээллийг талаарх ойлголтууд, уялдаа холбоог судлахын тулд түүний хэсгүүдэд задлах',
      verbs: [
        // { en: 'contrast', mn: 'ялгах' },
        // { en: 'connect', mn: 'холбох' },
        // { en: 'correlate', mn: 'хамаарлыг тогтоох' },
        // { en: 'illustrate', mn: 'дүрслэх' },
        // { en: 'conclude', mn: 'дүгнэх' },
        { en: 'categorize', mn: 'ангилах' },
        { en: 'organize', mn: 'зохион байгуулах' },
        { en: 'compare', mn: 'харьцуулах' },
        { en: 'contrast', mn: 'зүйрлүүлэх' },
        { en: 'analyze', mn: 'буцааж задлах' },
        { en: 'observe carefully', mn: 'ахинхааралтай ажиглах' },
        { en: 'experiment', mn: 'турших' },
        { en: 'evaluate', mn: 'дүгнэх' },
        { en: 'arrange', mn: 'цэгцлэх' },
        { en: 'systematize', mn: 'системчлэх' },
        { en: 'sequence', mn: 'дараалуулах' },
        { en: 'structure', mn: 'бүтцэд оруулах' },
        { en: 'synthesize', mn: 'нэгтгэн дүгнэх' },
      ],
    },
    {
      level: 3,
      english: 'APPLYING',
      mongolian: 'ХЭРЭГЛЭХ',
      description: 'Танил өөр нөхцөл байдалд мэдээллийг ашиглах',
      verbs: [
        // { en: 'solve', mn: 'шийдэх' },
        // { en: 'change', mn: 'загварчлах' },
        // { en: 'complete', mn: 'даалгаврыг хэрэгжүүлэх' },
        // { en: 'sketch', mn: 'загвар гаргах' },
        // { en: 'teach', mn: 'заах' },
        { en: 'discover', mn: 'олж илрүүлэх' },
        { en: 'perform', mn: 'хийж гүйцээх' },
        { en: 'execute', mn: 'гүйцэтгэх' },
        { en: 'carry out', mn: 'биелүүлэх' },
        { en: 'create', mn: 'бүтээх' },
        { en: 'implement', mn: 'хэрэгжүүлэх' },
        { en: 'develop', mn: 'боловсруулах' },
        { en: 'operate', mn: 'үйлдэх' },
        { en: 'sequence', mn: 'дараалуулах' },
      ],
    },
    {
      level: 2,
      english: 'UNDERSTANDING',
      mongolian: 'ОЙЛГОХ',
      description: 'Санаа бодол эсвэл ойлголтыг тайлбарлах',
      verbs: [
        // { en: 'summarize', mn: 'дүгнэх' },
        // { en: 'classify', mn: 'ангилах' },
        // { en: 'compare', mn: 'харьцуулах' },
        // { en: 'paraphrase', mn: 'орлуулах' },
        // { en: 'relate', mn: 'хамаарлыг тодорхойлох' },
        { en: 'describe', mn: 'онцлогийг тайлбарлах' },
        { en: 'classify', mn: 'ангилах' },
        { en: 'illustrate', mn: 'дүрслэн өгүүлэх' },
        { en: 'explain', mn: 'учрыг тайлбарлах' },
        { en: 'compare', mn: 'адилтгах' },
        { en: 'clarify', mn: 'ойлгуулах' },
        { en: 'summarize', mn: 'тоймлох /ноороглох/' },
        { en: 'identify', mn: 'таньж мэдэх' },
      ],
    },
    {
      level: 1,
      english: 'REMEMBER',
      mongolian: 'СЭРГЭЭН САНАХ',
      description: 'Мэдээллийг эргэн санах',
      verbs: [
        // { en: 'define', mn: 'тодорхойлох' },
        // { en: 'describe', mn: 'тайлбарлах' },
        // { en: 'explain', mn: 'тайлбарлах' },
        // { en: 'illustrate', mn: 'дүрслэх' },
        // { en: 'recognize', mn: 'таних' },

        { en: 'cite', mn: 'иш татах' },
        { en: 'search', mn: 'хайх' },
        { en: 'classify', mn: 'бүлэглэх' },
        { en: 'list', mn: 'жагсаах' },
        { en: 'locate', mn: 'байршлыг тогтоох' },
        { en: 'name', mn: 'нэрлэх' },
        { en: 'recall', mn: 'эргэж дурсах' },
        { en: 'copy', mn: 'хуулбарлах' },
        { en: 'obtain', mn: 'олж авах' },
        { en: 'remember', mn: 'дурсах' },
      ],
    },
  ];
}
